version: "3.8"

services:
  db:
    image: postgres:13
    container_name: postgres_test_db
    env_file:
      - .env.test
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5432"  # Expose a different port for testing
    volumes:
      - postgres_test_data:/var/lib/postgresql/data

  test:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_test
    depends_on:
      - db
    env_file:
      - .env.test
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: db
      DB_PORT: 5432
    volumes:
      - .:/app
    command: ["pytest", "tests/"]

volumes:
  postgres_test_data: